language: python

python:
  - 3.6

install:
  - pip install .
  - pip install coveralls

script:
  - coverage run setup.py test
  - pytest

after_success:
  - coveralls

notifications:
  - on_success: change
  - on_failure: always